// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKo9BNBN04_dDljJNBdqPU3iqGdx_lfq8',
    appId: '1:284704538070:android:53ddd107e244ce8d613877',
    messagingSenderId: '284704538070',
    projectId: 'myfirstapp-cf0e4',
    storageBucket: 'myfirstapp-cf0e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_6Ts2rEyAEugbZDSq0KDqswe0kqWO6Q',
    appId: '1:284704538070:ios:70a09a0cc030565d613877',
    messagingSenderId: '284704538070',
    projectId: 'myfirstapp-cf0e4',
    storageBucket: 'myfirstapp-cf0e4.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJ-kccASMD8vpLIAy6OZJFlfIKlr-EoY',
    appId: '1:284704538070:web:32f7015b84c43048613877',
    messagingSenderId: '284704538070',
    projectId: 'myfirstapp-cf0e4',
    authDomain: 'myfirstapp-cf0e4.firebaseapp.com',
    storageBucket: 'myfirstapp-cf0e4.firebasestorage.app',
    measurementId: 'G-NKTXZDPKKQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_6Ts2rEyAEugbZDSq0KDqswe0kqWO6Q',
    appId: '1:284704538070:ios:70a09a0cc030565d613877',
    messagingSenderId: '284704538070',
    projectId: 'myfirstapp-cf0e4',
    storageBucket: 'myfirstapp-cf0e4.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJ-kccASMD8vpLIAy6OZJFlfIKlr-EoY',
    appId: '1:284704538070:web:279b7599da933bcd613877',
    messagingSenderId: '284704538070',
    projectId: 'myfirstapp-cf0e4',
    authDomain: 'myfirstapp-cf0e4.firebaseapp.com',
    storageBucket: 'myfirstapp-cf0e4.firebasestorage.app',
    measurementId: 'G-5MK0E0K0PX',
  );

}